name: Release

on:
  push:
    branches:
      - deploy

jobs:
  build:
    name: Build
    runs-on: self-hosted
    outputs:
      version: ${{ steps.pkg.outputs.result }}

    steps:
      - uses: actions/checkout@v4
      - name: Read version from package.json
        id: pkg
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const fs = require('fs');
            const { version } = JSON.parse(fs.readFileSync('package.json', 'utf8'));
            return version;
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run dist
      - uses: actions/upload-artifact@v4
        with:
          name: out
          path: |
            out/*.exe
            out/*.AppImage
            out/*.dmg
            out/*.deb
            out/*.rpm
            out/*.zip
            out/*.tar.gz
          if-no-files-found: ignore

  release:
    name: Release
    needs: build
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Prepare artifacts folder
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            fs.rmSync('artifacts', { recursive: true, force: true });
            fs.mkdirSync('artifacts', { recursive: true });
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.build.outputs.version }}-${{ github.run_number }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          files: |
            artifacts/*.exe
            artifacts/*.AppImage
            artifacts/*.dmg
            artifacts/*.deb
            artifacts/*.rpm
            artifacts/*.zip
            artifacts/*.tar.gz
          fail_on_unmatched_files: true
